// The import below is generated by `opennextjs-cloudflare build` and doesn't
// exist at typecheck time. The build step creates it before wrangler bundles.
// @ts-expect-error — generated at build time
import openNextHandler from "./.open-next/worker.js"

// @ts-expect-error — generated at build time
export { DOQueueHandler } from "./.open-next/worker.js"

const handler: ExportedHandler<CloudflareEnv> = {
  async fetch(request, env, ctx) {
    const url = new URL(request.url)
    const isWsUpgrade = request.headers.get("Upgrade")?.toLowerCase() === "websocket"
    const isWsPath = url.pathname === "/api/ws" || url.pathname.startsWith("/api/ws/")

    // Forward WebSocket upgrades on /api/ws/* directly to the ws-do worker.
    // OpenNext drops Response.webSocket when wrapping Next.js route handlers
    // (opennextjs-cloudflare#784), so we intercept before Next.js sees it.
    // /api/ws/token is a plain HTTP endpoint — it has no Upgrade header and
    // falls through to OpenNext.
    if (isWsUpgrade && isWsPath) {
      return env.WS_DO_WORKER.fetch(request)
    }

    return (openNextHandler as ExportedHandler<CloudflareEnv>).fetch!(request, env, ctx)
  },
}

export default handler
